In [10]:
import sklearn
import numpy as np
import pandas as pd

Importing dataset

In [15]:
dataset_raw = pd.read_csv("dataset_183_adult.csv",header=0)
print(dataset_raw.head(10))

   age         workclass  fnlwgt  education  education-num  \
0    2         State-gov   77516  Bachelors             13   
1    3  Self-emp-not-inc   83311  Bachelors             13   
2    2           Private  215646    HS-grad              9   
3    3           Private  234721       11th              7   
4    1           Private  338409  Bachelors             13   
5    2           Private  284582    Masters             14   
6    3           Private  160187        9th              5   
7    3  Self-emp-not-inc  209642    HS-grad              9   
8    1           Private   45781    Masters             14   
9    2           Private  159449  Bachelors             13   

          marital-status         occupation   relationship   race     sex  \
0          Never-married       Adm-clerical  Not-in-family  White    Male   
1     Married-civ-spouse    Exec-managerial        Husband  White    Male   
2               Divorced  Handlers-cleaners  Not-in-family  White    Male   
3     Mar

Exploring unique values in dataset

In [30]:
for col in dataset_raw.columns:
    print("Column: " + col)
    print("Number of unique values: " + str(pd.unique(dataset_raw[col]).shape[0]))
    print(pd.unique(dataset_raw[col]))
    print("\n")

Column: age
Number of unique values: 5
[2 3 1 0 4]


Column: workclass
Number of unique values: 9
['State-gov' 'Self-emp-not-inc' 'Private' 'Federal-gov' 'Local-gov' '?'
 'Self-emp-inc' 'Without-pay' 'Never-worked']


Column: fnlwgt
Number of unique values: 28523
[ 77516  83311 215646 ... 173449  89686 350977]


Column: education
Number of unique values: 16
['Bachelors' 'HS-grad' '11th' 'Masters' '9th' 'Some-college' 'Assoc-acdm'
 'Assoc-voc' '7th-8th' 'Doctorate' 'Prof-school' '5th-6th' '10th'
 '1st-4th' 'Preschool' '12th']


Column: education-num
Number of unique values: 16
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]


Column: marital-status
Number of unique values: 7
['Never-married' 'Married-civ-spouse' 'Divorced' 'Married-spouse-absent'
 'Separated' 'Married-AF-spouse' 'Widowed']


Column: occupation
Number of unique values: 15
['Adm-clerical' 'Exec-managerial' 'Handlers-cleaners' 'Prof-specialty'
 'Other-service' 'Sales' 'Craft-repair' 'Transport-moving'
 'Farming-fishing' 

Since the dataset has mostly categorical data we will need to factorize them. 
On the other hand fnlwgt is a continuous number, so depending on the algorithm we are using we will need to normalize using either z-score or min-max

Factorizing the categorical data